### ISSUE TITLE
Generated client.ovpn not importing to OpenVpn with error.

### ISSUE THREAD

**Issue by vetermanve** [dockovpn/docker-openvpn#110]
So this is an error.
<img width="520" alt="Снимок экрана 2020-09-18 в 12 53 04" src="https://user-images.githubusercontent.com/744136/93584669-4aa25600-f9ae-11ea-925d-32e03cfbb36f.png">

On Tunnelblick (Mac Os)
Tunnelblick 3.8.4beta04 (build 5560)

Mac Os 10.15.6

CertFile
[client.ovpn.zip](https://github.com/alekslitvinenk/docker-openvpn/files/5244811/client.ovpn.zip)

Will be pleased for help!

**Comment by alekslitvinenk** [comment]
Hi Mikhail,

Thanks for reaching me out.
I think the problem is that your path containing client config contains '~' symbols which is causing this error.

================

Здравствуйте Михаил,

Я думаю проблема в том, что в пути по которому лежит клиентский файл присутствует недопустимый символ '~'
